# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ComicSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ComicSwift
inhibit_all_warnings!
pod 'SnapKit'
pod 'Alamofire'
pod 'MJRefresh'
pod 'KakaJSON'
pod 'HMSegmentedControl'
pod 'Moya'
pod 'Kingfisher'
pod 'Reusable'
pod 'LLCycleScrollView'
pod 'SwiftyJSON'
pod 'Then'
pod 'MBProgressHUD'
pod 'IQKeyboardManagerSwift'
pod 'EmptyDataSet-Swift'
pod 'UINavigation-SXFixSpace'
end
